require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CsMembersController do

  # This should return the minimal set of attributes required to create a valid
  # CsMember. As you add validations to CsMember, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all cs_members as @cs_members" do
      cs_member = CsMember.create! valid_attributes
      get :index
      assigns(:cs_members).should eq([cs_member])
    end
  end

  describe "GET show" do
    it "assigns the requested cs_member as @cs_member" do
      cs_member = CsMember.create! valid_attributes
      get :show, :id => cs_member.id.to_s
      assigns(:cs_member).should eq(cs_member)
    end
  end

  describe "GET new" do
    it "assigns a new cs_member as @cs_member" do
      get :new
      assigns(:cs_member).should be_a_new(CsMember)
    end
  end

  describe "GET edit" do
    it "assigns the requested cs_member as @cs_member" do
      cs_member = CsMember.create! valid_attributes
      get :edit, :id => cs_member.id.to_s
      assigns(:cs_member).should eq(cs_member)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CsMember" do
        expect {
          post :create, :cs_member => valid_attributes
        }.to change(CsMember, :count).by(1)
      end

      it "assigns a newly created cs_member as @cs_member" do
        post :create, :cs_member => valid_attributes
        assigns(:cs_member).should be_a(CsMember)
        assigns(:cs_member).should be_persisted
      end

      it "redirects to the created cs_member" do
        post :create, :cs_member => valid_attributes
        response.should redirect_to(CsMember.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cs_member as @cs_member" do
        # Trigger the behavior that occurs when invalid params are submitted
        CsMember.any_instance.stub(:save).and_return(false)
        post :create, :cs_member => {}
        assigns(:cs_member).should be_a_new(CsMember)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CsMember.any_instance.stub(:save).and_return(false)
        post :create, :cs_member => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cs_member" do
        cs_member = CsMember.create! valid_attributes
        # Assuming there are no other cs_members in the database, this
        # specifies that the CsMember created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CsMember.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => cs_member.id, :cs_member => {'these' => 'params'}
      end

      it "assigns the requested cs_member as @cs_member" do
        cs_member = CsMember.create! valid_attributes
        put :update, :id => cs_member.id, :cs_member => valid_attributes
        assigns(:cs_member).should eq(cs_member)
      end

      it "redirects to the cs_member" do
        cs_member = CsMember.create! valid_attributes
        put :update, :id => cs_member.id, :cs_member => valid_attributes
        response.should redirect_to(cs_member)
      end
    end

    describe "with invalid params" do
      it "assigns the cs_member as @cs_member" do
        cs_member = CsMember.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CsMember.any_instance.stub(:save).and_return(false)
        put :update, :id => cs_member.id.to_s, :cs_member => {}
        assigns(:cs_member).should eq(cs_member)
      end

      it "re-renders the 'edit' template" do
        cs_member = CsMember.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CsMember.any_instance.stub(:save).and_return(false)
        put :update, :id => cs_member.id.to_s, :cs_member => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cs_member" do
      cs_member = CsMember.create! valid_attributes
      expect {
        delete :destroy, :id => cs_member.id.to_s
      }.to change(CsMember, :count).by(-1)
    end

    it "redirects to the cs_members list" do
      cs_member = CsMember.create! valid_attributes
      delete :destroy, :id => cs_member.id.to_s
      response.should redirect_to(cs_members_url)
    end
  end

end
